### ISSUE TITLE
Unused test-environment.yaml file

### ISSUE THREAD

**Issue by ianthomas23** [jupyter-widgets/ipydatagrid#543]
There is a `test-environment.yaml` file in the base directory of the repo that doesn't appear to be used anywhere and has some old dependencies in it such as `nodejs=14`. I think it should either be removed, or updated to be more like `test-environment-ipyw8.yaml`.

**Comment by martinRenou** [comment]
Thanks! 

Let's remove it for the sake of simplifying the repositry
