### ISSUE TITLE
DataGrid to Pandas DataFrame

### ISSUE THREAD

**Issue by Castelloz** [jupyter-widgets/ipydatagrid#549]
Hello,

I have not found a way to transform the data from DataGrid to Python DataFrame.

Would appreciate if someone could share any solution for this.

Thanks

**Comment by martinRenou** [comment]
Isn't simply `datagrid.data` what you need?

**Comment by Castelloz** [comment]
Thank you for your quick reply.

I have a Pandas DataFrame and then use ipydatagrid to edit my data. When finished editing my data I would then like to Pandas DataFrametransform it back to a df.

Is there a solution for this?

**Comment by martinRenou** [comment]
Then what I just suggested works :)

Please look at this example: https://github.com/jupyter-widgets/ipydatagrid/blob/main/examples/CellEditing.ipynb

You'll see that `datagrid.data` provides the dataframe updated after edits

**Comment by Castelloz** [comment]
Thank you. I will have a look at it.

**Comment by Castelloz** [comment]
Thank you @martinRenou

Your line of code worked like a charm :)

Feel bad that I didn`t get it when I was looking at this example initially some weeks ago. Haha
